# Generated by Django 6.0.3 on 2026-03-30 13:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('organisation', 'user', 'pole', 'membership_type')},
        ),
    ]
