# Generated by Django 6.0.4 on 2026-05-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_alter_membership_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='pole',
            name='dsf_code',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Code IGN/DSF'),
        ),
    ]
