# Generated by Django 6.1 on 2026-09-17 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0004_remove_manager_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('prefix', models.CharField(editable=False, max_length=8, unique=True)),
                ('hashed_key', models.CharField(editable=False, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name="date d'expiration")),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='organisations.organisation', verbose_name='organisation')),
            ],
            options={
                'verbose_name': 'clé API',
                'verbose_name_plural': 'clés API',
            },
        ),
    ]
