# Generated by Django 6.1.1 on 2026-09-28 12:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0005_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='vocabulary_categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, verbose_name='catégories de vocabulaire accessibles'),
        ),
    ]
