# Generated by Django 6.0.2 on 2026-03-25 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(verbose_name='titre')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='date de début')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='date de fin')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='organisations.organisation')),
                ('pole', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='organisations.pole')),
            ],
            options={
                'verbose_name': 'campagne',
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(verbose_name='titre')),
                ('json_schema', models.JSONField(blank=True, null=True, verbose_name='schéma JSON')),
                ('survey_type', models.CharField(choices=[('self-contained', 'Enquête générale')], default='self-contained')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='surveys.campaign', verbose_name='campagne')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_surveys', to=settings.AUTH_USER_MODEL, verbose_name='créateur ou créatrice')),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveys', to='organisations.organisation')),
                ('pole', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveys', to='organisations.pole')),
            ],
            options={
                'verbose_name': 'enquête',
            },
        ),
        migrations.CreateModel(
            name='VocabularySet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField()),
                ('name', models.CharField(verbose_name='nom')),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vocabularies', to='organisations.organisation')),
            ],
            options={
                'verbose_name': 'set de vocabulaire',
                'unique_together': {('organisation', 'code')},
            },
        ),
        migrations.CreateModel(
            name='VocabularyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField()),
                ('label', models.CharField()),
                ('position', models.IntegerField(blank=True, null=True)),
                ('vocabulary_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='surveys.vocabularyset')),
            ],
            options={
                'verbose_name': 'entrée de vocabulaire',
                'unique_together': {('vocabulary_set', 'code')},
            },
        ),
    ]
