# Generated by Django 6.0.4 on 2026-04-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_historicalcampaign_historicalsurvey_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabularyentry',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
