# Generated by Django 6.0.6 on 2026-07-10 10:03

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0004_remove_manager_role'),
        ('surveys', '0003_vocabularyentry_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSurveyFollowUp',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('creation_date', models.DateTimeField(blank=True, editable=False)),
                ('modification_date', models.DateTimeField(blank=True, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('json_schema', models.JSONField(blank=True, null=True, verbose_name='schéma JSON')),
                ('title', models.CharField(verbose_name='titre')),
                ('action_label', models.CharField(max_length=100)),
                ('action_icon', models.CharField(blank=True, max_length=50)),
                ('action_color', models.CharField(blank=True, max_length=20)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créateur ou créatrice')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organisations.organisation')),
                ('parent_survey', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='surveys.survey')),
                ('pole', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organisations.pole')),
            ],
            options={
                'verbose_name': 'historical suivi',
                'verbose_name_plural': 'historical suivis',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SurveyFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('json_schema', models.JSONField(blank=True, null=True, verbose_name='schéma JSON')),
                ('title', models.CharField(verbose_name='titre')),
                ('action_label', models.CharField(max_length=100)),
                ('action_icon', models.CharField(blank=True, max_length=50)),
                ('action_color', models.CharField(blank=True, max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_survey_follow_ups', to=settings.AUTH_USER_MODEL, verbose_name='créateur ou créatrice')),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_follow_ups', to='organisations.organisation')),
                ('parent_survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='surveys.survey')),
                ('pole', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_follow_ups', to='organisations.pole')),
            ],
            options={
                'verbose_name': 'suivi',
            },
        ),
    ]
