# Generated by Django 6.0.6 on 2026-07-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_historicalsurveyfollowup_surveyfollowup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsurveyfollowup',
            name='action_label',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='surveyfollowup',
            name='action_label',
            field=models.CharField(blank=True),
        ),
    ]
