# Generated by Django 6.1 on 2026-09-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_alter_historicalsurveyfollowup_action_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvocabularyset',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='actif'),
        ),
        migrations.AddField(
            model_name='vocabularyset',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='actif'),
        ),
    ]
