# Generated by Django 6.1.1 on 2026-09-28 12:30

from django.db import migrations, models


def assign_forest_category(apps, schema_editor):
    """Assigne la catégorie 'forest' à tous les VocabularySet existants."""
    VocabularySet = apps.get_model("surveys", "VocabularySet")
    VocabularySet.objects.filter(category__isnull=True).update(category="forest")


def reverse_assign_forest_category(apps, schema_editor):
    """Rétablit category=None sur les sets qui avaient été assignés à 'forest'."""
    VocabularySet = apps.get_model("surveys", "VocabularySet")
    VocabularySet.objects.filter(category="forest").update(category=None)


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_historicalvocabularyset_is_active_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vocabularyset',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='historicalvocabularyset',
            name='category',
            field=models.CharField(blank=True, choices=[('forest', 'Forêt')], max_length=50, null=True, verbose_name='catégorie'),
        ),
        migrations.AddField(
            model_name='vocabularyset',
            name='category',
            field=models.CharField(blank=True, choices=[('forest', 'Forêt')], max_length=50, null=True, verbose_name='catégorie'),
        ),
        migrations.RunPython(assign_forest_category, reverse_code=reverse_assign_forest_category),
        migrations.AlterUniqueTogether(
            name='vocabularyset',
            unique_together={('category', 'code')},
        ),
    ]
