# Generated by Django 6.0.2 on 2026-03-25 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('surveys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'Envoyé'), ('exported', 'Exporté')], default='draft', verbose_name='statut')),
                ('data', models.JSONField(verbose_name='données')),
                ('submission_date', models.DateTimeField(blank=True, null=True, verbose_name='date de soumission')),
                ('context', models.JSONField(blank=True, null=True)),
                ('respondant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to=settings.AUTH_USER_MODEL, verbose_name='répondant ou répondante')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='surveys.survey', verbose_name='enquête')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
