# Generated by Django 6.0.3 on 2026-04-17 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0002_historicalresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalresponse',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'Envoyé'), ('exported', 'Exporté')], default='submitted', verbose_name='statut'),
        ),
        migrations.AlterField(
            model_name='response',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'Envoyé'), ('exported', 'Exporté')], default='submitted', verbose_name='statut'),
        ),
    ]
