# Generated by Django 6.0.5 on 2026-05-26 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0003_alter_historicalresponse_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('file', models.ImageField(upload_to='response_images/%Y/%m/')),
                ('name', models.TextField(blank=True, verbose_name='nom du fichier')),
                ('thumbnail', models.ImageField(upload_to='response_thumbnails/%Y/%m/')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='responses.response')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
