# Generated by Django 6.0.5 on 2026-05-28 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0004_responseimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responseimage',
            name='name',
        ),
    ]
