# Generated by Django 6.0.5 on 2026-06-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0005_remove_responseimage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalresponse',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='response',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
