# Generated by Django 6.0.6 on 2026-07-10 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0006_historicalresponse_is_active_response_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalresponse',
            name='parent_response',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='responses.response'),
        ),
    ]
