# Generated by Django 6.0.6 on 2026-07-10 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0007_historicalresponse_parent_response'),
        ('surveys', '0004_historicalsurveyfollowup_surveyfollowup'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalresponse',
            name='survey_follow_up',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='surveys.surveyfollowup'),
        ),
        migrations.AddField(
            model_name='response',
            name='parent_response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_up_responses', to='responses.response'),
        ),
        migrations.AddField(
            model_name='response',
            name='survey_follow_up',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='surveys.surveyfollowup'),
        ),
        migrations.AlterField(
            model_name='response',
            name='survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='surveys.survey', verbose_name='enquête'),
        ),
    ]
