# Generated by Django 6.0.6 on 2026-07-11 17:44

import django.contrib.gis.db.models.fields
from django.contrib.gis.geos import Point
from django.db import migrations


def backfill_geolocation_points(apps, schema_editor):
    Response = apps.get_model("responses", "Response")

    for response in Response.objects.filter(
        geolocation_point__isnull=True, survey__isnull=False
    ).select_related("survey"):
        try:
            schema = response.survey.json_schema
            if not schema or not isinstance(schema, dict):
                continue

            map_field = next(
                (
                    f
                    for f in schema.get("fields", [])
                    if isinstance(f, dict)
                    and f.get("ui", {}).get("widget") == "map"
                ),
                None,
            )
            if not map_field:
                continue

            field_id = map_field.get("id")
            if not field_id:
                continue

            data = response.data
            if not isinstance(data, dict):
                continue

            value = data.get(field_id)
            if not isinstance(value, dict):
                continue

            lat = value.get("lat")
            lon = value.get("lon")
            if isinstance(lat, (int, float)) and isinstance(lon, (int, float)):
                response.geolocation_point = Point(lon, lat, srid=4326)
                response.save(update_fields=["geolocation_point"])
        except Exception:
            continue


class Migration(migrations.Migration):

    dependencies = [
        ("responses", "0008_historicalresponse_survey_follow_up_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalresponse",
            name="geolocation_point",
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name="Localisation"),
        ),
        migrations.AddField(
            model_name="response",
            name="geolocation_point",
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name="Localisation"),
        ),
        migrations.RunPython(backfill_geolocation_points, migrations.RunPython.noop),
    ]
