# Generated by Django 6.0.7 on 2026-08-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0009_historicalresponse_geolocation_point_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalresponse',
            name='client_id',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='identifiant client'),
        ),
        migrations.AddField(
            model_name='response',
            name='client_id',
            field=models.UUIDField(blank=True, null=True, unique=True, verbose_name='identifiant client'),
        ),
    ]
