# Generated by Django 6.0.4 on 2026-04-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='external_id',
            field=models.CharField(blank=True, help_text='Identifiant dans le système source (ex: code CO dans dsfp)', null=True, verbose_name='identifiant externe'),
        ),
        migrations.AddField(
            model_name='user',
            name='source',
            field=models.CharField(choices=[('local', 'Local'), ('dsf', 'DSF (dsfp)')], default='local', max_length=20, verbose_name="source d'authentification"),
        ),
    ]
