# Generated by Django 6.0.4 on 2026-05-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_external_id_user_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dsf_last_claims',
            field=models.JSONField(blank=True, null=True, verbose_name="Dernière information de la part de l'IGN/DSF"),
        ),
    ]
