/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers: never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/A11yPage': RouteRecordInfo<
      '/A11yPage',
      '/a11y',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/HomePage': RouteRecordInfo<
      '/HomePage',
      '/accueil',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/CookiesPage': RouteRecordInfo<
      '/CookiesPage',
      '/cookies',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/DashboardPage': RouteRecordInfo<
      '/DashboardPage',
      '/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/PrivacyPolicyPage': RouteRecordInfo<
      '/PrivacyPolicyPage',
      '/donnees-personnelles',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/LegalNoticesPage': RouteRecordInfo<
      '/LegalNoticesPage',
      '/mentions-legales',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/NotFoundPage': RouteRecordInfo<
      '/NotFoundPage',
      '/page-non-trouvée',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ResponseListPage/': RouteRecordInfo<
      '/ResponseListPage/',
      '/reponses',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ResponsePage/': RouteRecordInfo<
      '/ResponsePage/',
      '/response/:id',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/LoginPage': RouteRecordInfo<
      '/LoginPage',
      '/s-identifier',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/SurveyCreationPage/': RouteRecordInfo<
      '/SurveyCreationPage/',
      '/creation-enquete',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/SurveyListPage/': RouteRecordInfo<
      '/SurveyListPage/',
      '/enquetes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/SurveyPage/': RouteRecordInfo<
      '/SurveyPage/',
      '/enquete/:id',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/A11yPage.vue': {
      routes:
        | '/A11yPage'
      views:
        | never
    }
    'src/pages/HomePage.vue': {
      routes:
        | '/HomePage'
      views:
        | never
    }
    'src/pages/CookiesPage.vue': {
      routes:
        | '/CookiesPage'
      views:
        | never
    }
    'src/pages/DashboardPage.vue': {
      routes:
        | '/DashboardPage'
      views:
        | never
    }
    'src/pages/PrivacyPolicyPage.vue': {
      routes:
        | '/PrivacyPolicyPage'
      views:
        | never
    }
    'src/pages/LegalNoticesPage.vue': {
      routes:
        | '/LegalNoticesPage'
      views:
        | never
    }
    'src/pages/NotFoundPage.vue': {
      routes:
        | '/NotFoundPage'
      views:
        | never
    }
    'src/pages/ResponseListPage/index.vue': {
      routes:
        | '/ResponseListPage/'
      views:
        | never
    }
    'src/pages/ResponsePage/index.vue': {
      routes:
        | '/ResponsePage/'
      views:
        | never
    }
    'src/pages/LoginPage.vue': {
      routes:
        | '/LoginPage'
      views:
        | never
    }
    'src/pages/SurveyCreationPage/index.vue': {
      routes:
        | '/SurveyCreationPage/'
      views:
        | never
    }
    'src/pages/SurveyListPage/index.vue': {
      routes:
        | '/SurveyListPage/'
      views:
        | never
    }
    'src/pages/SurveyPage/index.vue': {
      routes:
        | '/SurveyPage/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
